name: BIKERLATAM
favicon: null
layout_spectrum: 0.34515
typography_spectrum: 0.8825047027785331
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9109533396549523
  lightness: 0.030053547583520412
  saturation: 0.258175052003935
  rhythmicContrast: 0.75
purpose: []
