name: BIKERLATAM
favicon: null
layout_spectrum: 0.53824
typography_spectrum: 0.31278
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3d9bf'
    - '#cc996c'
    - '#7d4546'
    - '#a16654'
    - '#6697a6'
  brandStrength: 0.6875
  lightness: 0.9375
  saturation: 0.4375
  rhythmicContrast: 0
purpose: []
