name: BIKERLATAM
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31278
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3d9bf'
    - '#cc996c'
    - '#7d4546'
    - '#a16654'
    - '#6697a6'
  brandStrength: 0.5625
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
